"""create demo

Revision ID: 8125ce6a58d2
Revises: 
Create Date: 2025-05-01 02:32:32.271680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8125ce6a58d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'demo',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=16), nullable=False, comment='Name, unique identifier'),
        sa.Column('age', sa.Integer(), nullable=True, comment='Age'),
        sa.Column('password', sa.String(length=32), nullable=True, comment='Password'),
        sa.Column('gender', sa.Integer(), nullable=True, comment='Refer to Gender enum'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_by', sa.String(length=32), nullable=False, comment='Update User Name'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo', schema='public')
    # ### end Alembic commands ###
